remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
description: [An isolated bootstrap version to avoid conflict with existing styles.]
show_downloads: "false"
# google_analytics: [Your Google Analytics tracking ID]
